name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PostgresSQL setup
        uses: harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: '13'
          postgresql db: alerttodb
          postgresql user: postgres
          postgresql password: postgres
      - name: Check Postgres running
        run: |
          sleep 10s
          PGPASSWORD=postgres psql -U postgres -h localhost -p 5432 -c "create database alerttocare"
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
